name: Auto-assign reviewers

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Assign reviewers
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: '.github/auto_assign.yml'
